### PR TITLE
add_user_mapping: bugfix

### PR DESCRIPTION
**Pull request by BlueAmulet**
Same fix as ead22426c48c64a6fea85dac8e9db783241617ec

### CODE REVIEW

**Review by SergeGautherie — APPROVED** [review]

**Comment by SergeGautherie** [comment]
> ead2242

which was reported as #330.

**Comment by SergeGautherie** [comment]
@maharmstone, something wrong happened with this PR:
* Your added commits should not be part of it. (Is that a fallout of the master branch reset after v1.7.5?)
* @BlueAmulet's fix was never committed.

**Comment by BlueAmulet** [comment]
I'd gave up after waiting a month for a simple bug fix identical to a previous accepted one to be looked at only for the pr to be completely destroyed by a force push.

**Comment by maharmstone** [comment]
Why on earth did you close it if you thought it was still valid?? I started looking into this a few days earlier, came to the conclusion that it may or may not be valid, and then when you closed it I assumed you'd already decided yourself...

**Pull request closed without merging**
