### PR TITLE
write_file2(): Fix a memory leak

### PR DESCRIPTION
**Pull request by SergeGautherie**
See #164: ReactOS "overwrite" testcase.
Tested on ReactOS. It feels odd that you don't reproduce on Windows...

==>
- Please, double-check the missing free should happen there.

### CODE REVIEW

**Comment by maharmstone** [comment]
Thanks Serge. What's the benefit to using ExFreePoolWithTag over ExFreePool?

**Comment by ale5000-git** [comment]
Quote:
```
A function that received a new version was ExFreePool(), its new version is the ExFreePoolWithTag(), which is implemented since Windows 2000.
...
The new version came to help detecting memory leaks. Each memory allocation is associated with a tag. These tags can be viewed using debugging tools such as WinDbg. For example: If your entire library setup uses a tag, and its communication library uses another, it will be easy to know which ones are leaving allocated memory. This makes it easy to know which programmer on your team you will be fired.
```

**Comment by SergeGautherie** [comment]
> What's the benefit to using ExFreePoolWithTag over ExFreePool?

The former is more explicit (code) and stricter (runtime).
It is the next step after using `ExAllocatePoolWithTag()`.

No tag case: `ExFreePoolWithTag(m, 0) == ExFreePool(m)`.
Also to be used when tag (= allocation) can vary.

Tag case: `ExFreePoolWithTag(m, aTag) == ExFreePool(m)` after it checked tags match.
This detects coding errors (wrong tag) and some runtime corruption cases (overflow/underflow/...).

**Comment by maharmstone** [comment]
Hmm, I'm not sure. I don't think checking for programming mistakes has any place in production code, as it'll slow it down - plus you can always use Driver Verifier to find any overflow issues, anyway. I'm struggling to think of any situation where you actually deallocate somebody else's memory...

**Comment by ale5000-git** [comment]
You could use a macro that use it only if compiled with debug enabled.

**Comment by SergeGautherie** [comment]
> I'm not sure

I understand and mostly agree, though I am not fully convinced in this very case.
Anyway, no debate here.

> setup a macro

Indeed! I concur.
In ReactOS, I would use `#ifndef DBG`. How should that be done in WinBtrfS?

**Comment by SergeGautherie** [comment]
Making progress (code and other leaks), I'll update this PR "soon".

**Comment by Extravert-ir** [comment]
> Hmm, I'm not sure. I don't think checking for programming mistakes has any place in production code, as it'll slow it down - plus you can always use Driver Verifier to find any overflow issues, anyway. I'm struggling to think of any situation where you actually deallocate somebody else's memory...

This check is done only on checked builds of Windows, so using `ExFreePoolWithTag` does not make _any_ performance impact on "production"

**Comment by SergeGautherie** [comment]
Split off additional improvements.

--

Superseded by 9d45a7ef3d8e92110513a713cfd496b10ea46dcb.

**Pull request closed without merging**
