### PR TITLE
FormatEx2: Fix a Visual Studio warning C4267 on x64

### PR DESCRIPTION
**Pull request by SergeGautherie**
No behavior change, only a bit better code.

### CODE REVIEW

**Comment by maharmstone** [comment]
Which version of MSVC throws this warning? I don't remember seeing one in VS2019.

**Comment by SergeGautherie** [comment]
At least, VS2017 and VS2019, as installed on AppVeyor CI:
`...\src\ubtrfs\ubtrfs.c(1237,75): warning C4267: '=': conversion from 'size_t' to 'ULONG', possible loss of data [...\ubtrfs.vcxproj]`

`offsetof()` returns a `size_t `, so it is pretty obvious anyway.

**Comment by ale5000-git** [comment]
Partially fixed here: https://github.com/maharmstone/btrfs/commit/664cefc191aa0cdd701f016bcc068a0940a12399

**Comment by SergeGautherie** [comment]
Indeed. Updaded.

**Comment by maharmstone** [comment]
Thank Serge, but I'm not interested in purely stylistic changes. Sorry.

**Pull request closed without merging**
